name: Gesture Speak CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
         pytest -v tests/test_dataset.py
         pytest -v tests/test_model.py
         pytest -v tests/test_train.py


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install streamlit

      - name: Run tests
        run: pytest -v tests/test_depl.py
        
      - name: Deploy with Streamlit
        run: |
          streamlit run pages/Check_From_Images.py &
          sleep 3
          echo "Stopping Streamlit after 10 seconds."
          pkill -f "streamlit run pages/Check_From_Images.py"
          streamlit run Real_Time_Recognition.py &
          sleep 3
          echo "Stopping Streamlit after 10 seconds."
          pkill -f "streamlit run Real_Time_Recognition.py"

